redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/shanirshad/CascadeProjects/windsurf-project/terminal-portfolio/react-portfolio/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install && npm run build"
base = "/Users/shanirshad/CascadeProjects/windsurf-project/terminal-portfolio/react-portfolio"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]